apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kafka-rest-deploy"
  labels:
    app: kafka-rest-deploy
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-rest-deploy
  template:
    metadata:
      labels:
        app: kafka-rest-deploy
    spec:
      containers:
      - name: kafka-rest
        image: "confluentinc/cp-kafka-rest:5.0.0"
        imagePullPolicy: "IfNotPresent"
        env:
          - name: KAFKA_REST_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          - name: KAFKA_REST_SCHEMA_REGISTRY_URL
            value: http://schema-registry:8081
          - name: KAFKA_REST_LISTENERS
            value: http://0.0.0.0:8082
          - name: KAFKA_REST_HOST_NAME
            value: kafka-rest
        ports:
         - containerPort: 8082
