apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka-deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kafka-deploy"
  labels:
    app: kafka-deploy
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-deploy
  template:
    metadata:
      labels:
        app: kafka-deploy
    spec:
      containers:
      - name: kafka
        image: "confluentinc/cp-kafka:5.0.0"
        imagePullPolicy: "IfNotPresent"
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "PLAINTEXT:PLAINTEXT"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://kafka-service:9092"
          - name: KAFKA_LISTENERS
            value: "PLAINTEXT://0.0.0.0:9092"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "PLAINTEXT"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
        ports:
        - containerPort: 9092