apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: kafka
spec:
  ports:
  - port: 8083
  selector:
    app: kafka-connect-deploy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-script
  namespace: kafka
data:
  config-mqtt.sh: |
    echo "configuracion"
    while true; do echo "y"; done | confluent-hub install confluentinc/kafka-connect-mqtt:1.2.3;
    mkdir /usr/share/java/kafka-connect-mqtt;
    cp -Rf /usr/share/confluent-hub-components/confluentinc-kafka-connect-mqtt/lib/* /usr/share/java/kafka-connect-mqtt;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kafka-connect-deploy"
  labels:
    app: kafka-connect-deploy
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect-deploy
  template:
    metadata:
      labels:
        app: kafka-connect-deploy
    spec:
      volumes:
      - name: config-script
        configMap:
          name: config-script
          defaultMode: 0777
      containers:
      - name: kafka-connect
        image: "confluentinc/cp-kafka-connect:5.0.0"
        imagePullPolicy: "Always"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", /config-script/config-mqtt.sh ]
        env:
          - name: CONNECT_PRODUCER_INTERCEPTOR_CLASSES
            value: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
          - name: CONNECT_CONSUMER_INTERCEPTOR_CLASSES
            value: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
          - name: CONNECT_BOOTSTRAP_SERVERS
            value: kafka-service:9092
          - name: CONNECT_REST_PORT
            value: "8083"
          - name: CONNECT_GROUP_ID
            value: quickstart
          - name: CONNECT_CONFIG_STORAGE_TOPIC
            value: quickstart-config
          - name: CONNECT_OFFSET_STORAGE_TOPIC
            value: quickstart-offsets
          - name: CONNECT_STATUS_STORAGE_TOPIC
            value: quickstart-status
          - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
            value: "1"
          - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
            value: "1"
          - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
            value: "1"
          - name: CONNECT_KEY_CONVERTER
            value: io.confluent.connect.avro.AvroConverter
          - name: CONNECT_VALUE_CONVERTER
            value: io.confluent.connect.avro.AvroConverter
          - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
            value: http://schema-registry:8081
          - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
            value: http://schema-registry:8081
          - name: CONNECT_INTERNAL_KEY_CONVERTER
            value: org.apache.kafka.connect.json.JsonConverter
          - name: CONNECT_INTERNAL_VALUE_CONVERTER
            value: org.apache.kafka.connect.json.JsonConverter
          - name: CONNECT_REST_ADVERTISED_HOST_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: CONNECT_LOG4J_ROOT_LOGLEVEL
            value: DEBUG
          - name: CONNECT_PLUGIN_PATH
            value: /usr/share/java
        ports:
         - containerPort: 8083
        volumeMounts:
          - mountPath: /config-script
            name: config-script