apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
spec:
  ports:
  - port: 2181
  selector:
    app: zookeeper-deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zookeeper-deploy"
  labels:
    app: zookeeper-deploy
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-deploy
  template:
    metadata:
      labels:
        app: zookeeper-deploy
    spec:
      containers:
      - name: zookeeper
        image: "confluentinc/cp-zookeeper:5.0.0"
        imagePullPolicy: "IfNotPresent"
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
        ports:
        - containerPort: 2181